public enum SortField {
    STRIKINGRATES, AVG,SIXFOURS, MAXSTRIKERATE_WITH_SIXFOUR, BESTAVERAGE_WITH_STRIKERATE, MAXRUNS_WITH_BESTAVERAGES, ECONOMYRATE, MAXWICKETS_WITH_STRIKERATE;
    public static SortField uc3;
}
