public enum SortField {
    STRIKINGRATES,ALLROUNDER,ALLROUNDERAVG,AVG,SIXFOURS, MAXSTRIKERATE_WITH_SIXFOUR, BESTAVERAGE_WITH_STRIKERATE, MAXRUNS_WITH_BESTAVERAGES, ECONOMYRATE, WICKETS4AND6_WITH_STRIKERATE, WICKETSAND_WITH_STRIKERATE, WICKETS_WITH_STRIKERATE;

}
